# Generated by Django 3.2 on 2023-02-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('time_add', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=200)),
                ('plane', models.CharField(max_length=200)),
                ('customer_ip', models.CharField(max_length=50)),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('nationalId', models.CharField(max_length=200)),
            ],
        ),
    ]
