# Generated by Django 3.2 on 2023-02-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='number2',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
