# Generated by Django 3.2 on 2023-02-18 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.generate_code


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('type', models.CharField(choices=[('Home', 'Home'), ('Office', 'Office'), ('Bussines', 'Bussines'), ('Academy', 'Academy'), ('Others', 'Others')], max_length=10, verbose_name='Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserPhone', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Profile')),
                ('code', models.CharField(default=utils.generate_code.generaste_code, max_length=8, verbose_name='Code')),
                ('code_used', models.BooleanField(default=False, verbose_name='Code Used')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
